###微信服务接口实现->服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-pri-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
####swagger相关配置
swagger:
  base-package: com.pri.weixin.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有。
  version: 1.1
  terms-of-service-url: www.mayikt.com
  contact:
    name: pri_chen
    email: 1024@qq.com


